# Generated by Django 2.0.10 on 2019-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carssection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carssection',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
